#!/bin/sh

set -e

echo "Installing Homebrew packages..."
brew update
brew tap homebrew/bundle
brew bundle

brew unlink qt 2>/dev/null || true
brew link --force qt5

echo "Linking dotfiles into ~ ..."
# Before `rcup` runs, there is no ~/.rcrc, so we must tell `rcup` where to look.
# We need the rcrc because it tells `rcup` to ignore thousands of useless Vim
# backup files that slow it down significantly.

# Remove everything in there now, using `rcrc` as the rcrc.
RCRC=rcrc rcdn -v

# Install everything, using `rcrc` as the rcrc.
RCRC=rcrc rcup -v

echo "Installing Vim packages..."
vim +PlugInstall +qa
